# Generated by Django 4.2.16 on 2024-11-16 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0009_curso_matricula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='costo',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='docente',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='curso',
        ),
        migrations.AlterField(
            model_name='matricula',
            name='date_joined',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso.curso')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso.docente')),
            ],
        ),
        migrations.AddField(
            model_name='matricula',
            name='sesion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='curso.sesion'),
        ),
    ]
