# Generated by Django 4.2.16 on 2024-11-16 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0011_curso_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='fecha',
        ),
        migrations.AddField(
            model_name='curso',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='curso.docente'),
        ),
        migrations.AddField(
            model_name='curso',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='usuarios_registrados',
            field=models.ManyToManyField(blank=True, to='curso.usuario'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
