# Generated by Django 4.2.16 on 2024-11-22 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0017_asesoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asesoria',
            name='link',
        ),
    ]
