# Generated by Django 5.0.2 on 2024-10-06 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
