# Generated by Django 5.1.1 on 2024-10-13 05:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0004_usuario_contrasena'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=50, unique=True)),
                ('expiration', models.DateTimeField(default=datetime.datetime(2024, 10, 13, 6, 54, 19, 152738, tzinfo=datetime.timezone.utc))),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso.usuario')),
            ],
        ),
    ]
