# Generated by Django 4.2.16 on 2024-11-16 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0010_remove_curso_costo_remove_curso_docente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='fecha',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
    ]
