# Generated by Django 4.2.16 on 2024-11-16 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0012_remove_curso_fecha_curso_docente_curso_fecha_fin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='usuarios_registrados',
        ),
        migrations.AddField(
            model_name='curso',
            name='usuario_registrado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='curso.usuario'),
        ),
    ]
