# Generated by Django 4.2.16 on 2024-11-16 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0013_remove_curso_usuarios_registrados_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='usuario_registrado',
        ),
        migrations.AddField(
            model_name='curso',
            name='usuarios_registrados',
            field=models.ManyToManyField(blank=True, to='curso.usuario'),
        ),
    ]
