# Generated by Django 4.2.16 on 2024-11-21 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0014_remove_curso_usuario_registrado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField(default=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso.sesion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso.usuario')),
            ],
        ),
    ]
