# Generated by Django 4.2.16 on 2024-11-21 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0015_asistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesion',
            name='duracion',
            field=models.IntegerField(default=60),
        ),
    ]
