# Generated by Django 4.2.16 on 2024-11-22 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0018_remove_asesoria_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asesoria',
            name='descripcion',
        ),
    ]
