# Generated by Django 4.2.16 on 2024-11-22 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0019_remove_asesoria_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matricula',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='sesion',
        ),
        migrations.AddField(
            model_name='matricula',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='curso.curso'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='fecha_matricula',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
