# Generated by Django 4.2.16 on 2024-11-22 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0021_sugerencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sugerencia',
            name='usuario',
        ),
    ]
