# Generated by Django 5.1.3 on 2024-11-23 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0027_evidencia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Evidencia',
        ),
    ]
