# Generated by Django 5.1.3 on 2024-11-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0032_encuesta_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='metodo_pago',
            field=models.CharField(choices=[('transferencia', 'Transferencia Bancaria'), ('credito', 'Tarjeta de Crédito'), ('debito', 'Tarjeta de Débito')], default='transferencia', max_length=50),
        ),
    ]
