# Generated by Django 5.1.3 on 2024-11-24 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0033_usuario_metodo_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc1', models.FloatField()),
                ('pc2', models.FloatField()),
                ('pc3', models.FloatField()),
                ('pc4', models.FloatField()),
                ('comentario', models.TextField()),
            ],
        ),
    ]
