# Generated by Django 5.1.3 on 2024-11-24 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0035_remove_evaluacion_comentario_remove_evaluacion_pc1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='pregunta1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='pregunta2',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='pregunta3',
            field=models.CharField(max_length=255),
        ),
    ]
